#!/usr/bin/env bash
# Pulsar Physics-Gen — cron wrapper for self-hosted deployment.
#
# Primary deploy is GitHub Actions (.github/workflows/pulsar-physics-gen-daily.yml).
# This wrapper is the self-hosted backup, kept for parity with the sister handbooks.
#
# Usage in crontab:
#   40 8 * * 1-5 /path/to/Physics-Controllable-Generation-Handbook/scripts/pulsar/cron_runner.sh
#
# Required env (set in crontab or a sourced file):
#   DASHSCOPE_API_KEY  — Aliyun qwen3.5-plus API key
#
# Optional env:
#   PULSAR_LOG_DIR     — log directory (default: /tmp)
#   PULSAR_NO_PUSH=1   — run pipeline, commit locally, but skip git push
#   PULSAR_NO_COMMIT=1 — run pipeline only, no git ops at all
#
# Safety / design:
#   - flock prevents concurrent runs (lock file in /tmp)
#   - git add scoped to reports/physics-gen-daily/ only (won't touch unrelated WIP)
#   - the dated archive is committed BEFORE auditing; the full-handbook audit runs
#     afterwards as an informational signal only and never blocks/reverts the archive
#     (lesson from the sister Spatial pipeline: an unrelated audit FAIL must not
#     silently discard the day's report).
#   - skip commit if no new content (e.g. weekend, zero qualifying papers)
#   - pull --rebase before push to minimize conflicts with other agents

set -euo pipefail

# --- Paths -----------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_DIR="${PULSAR_LOG_DIR:-/tmp}"
LOCK_FILE="${LOG_DIR}/pulsar-physics-gen.lock"
LOG_FILE="${LOG_DIR}/pulsar-physics-gen-$(date +%F).log"

# --- Lock (prevent concurrent runs) ---------------------------------
exec 200>"$LOCK_FILE"
if ! flock -n 200; then
  echo "[$(date -Iseconds)] Another instance running, exit." >&2
  exit 0
fi

# --- Log rotation (auto-trim 30 day) --------------------------------
find "$LOG_DIR" -name "pulsar-physics-gen-*.log" -mtime +30 -delete 2>/dev/null || true

# --- Tee output to log + stderr -------------------------------------
exec > >(tee -a "$LOG_FILE") 2>&1

echo ""
echo "════════════════════════════════════════════════════════════"
echo "[$(date -Iseconds)] Pulsar Physics-Gen cron start"
echo "  REPO_ROOT=$REPO_ROOT"
echo "  LOG_FILE=$LOG_FILE"
echo "════════════════════════════════════════════════════════════"

# --- Sanity ----------------------------------------------------------
if [ -z "${DASHSCOPE_API_KEY:-}" ]; then
  echo "ERROR: DASHSCOPE_API_KEY not set" >&2
  exit 1
fi

cd "$REPO_ROOT"

# --- 1. Run pipeline ------------------------------------------------
echo ""
echo "--- Stage 1: Run Pulsar pipeline ---"
if ! python3 scripts/pulsar/run_daily.py; then
  echo "ERROR: pipeline failed, abort." >&2
  exit 2
fi

# --- 2. Commit + push (unless flagged off) --------------------------
if [ "${PULSAR_NO_COMMIT:-}" = "1" ]; then
  echo ""
  echo "PULSAR_NO_COMMIT=1, skip git ops. Done."
  exit 0
fi

echo ""
echo "--- Stage 2: git commit + push (archive first, before audit) ---"

# Scope add to physics-gen-daily only (safe — won't touch unrelated WIP)
git add reports/physics-gen-daily/

# Skip if no new files
if git diff --staged --quiet; then
  echo "No new physics-gen-daily content — skip commit."
else
  # Pull latest before commit (avoid concurrent agent conflicts)
  git pull --rebase origin main || {
    echo "ERROR: rebase failed, manual intervention needed." >&2
    exit 4
  }

  DATE=$(date +%F)
  git -c user.name="Pulsar Bot" \
      -c user.email="noreply@anthropic.com" \
      commit -m "auto(pulsar): physics-gen daily ${DATE}

Generated by cron_runner.sh on $(hostname)
Pipeline: collect.py → rate.py (qwen3.5-plus) → post.py"

  if [ "${PULSAR_NO_PUSH:-}" = "1" ]; then
    echo "PULSAR_NO_PUSH=1, commit done but skip push."
  else
    # Retry push once on conflict
    if ! git push origin main; then
      echo "Push conflict, retrying after rebase..."
      git pull --rebase origin main
      git push origin main
    fi
  fi
fi

# --- 3. Informational audit (never blocks the archive committed above) ---
echo ""
echo "--- Stage 3: sync README + handbook audit (informational) ---"
python3 scripts/sync_readme_from_overview.py || true
python3 scripts/handbook_audit.py || echo "  (audit reported issues — informational only; see audit.yml gate)"

echo ""
echo "════════════════════════════════════════════════════════════"
echo "[$(date -Iseconds)] Pulsar Physics-Gen cron done ✅"
echo "════════════════════════════════════════════════════════════"
